name: Deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOTNET_VERSION: 8.0.x
  SOLUTION_FILE: ./RichillCapital.TraderStudio.Web.sln
  CONFIGURATION: Release
  AZURE_WEB_APP_NAME: richillcapital-trader-studio-web
  AZURE_WEB_APP_PACKAGE_PATH: ./publish

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build ${{ env.SOLUTION_FILE }} --no-restore
      
    - name: Test
      run: dotnet test ${{ env.SOLUTION_FILE }} -c ${{ env.CONFIGURATION }} --no-restore --no-build
    
    - name: Publish
      run: dotnet publish ${{ env.SOLUTION_FILE }} -c ${{ env.CONFIGURATION }} --no-restore --no-build -o ./publish

    - name: Deployment (Azure App Service)
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEB_APP_NAME }}
        package: ${{ env.AZURE_WEB_APP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_APP_SERVICE_PUBLISH_PROFILE }}
        slot-name: production